name = "Distant Horizons Benchmark"
author = "Steveplays28"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adb6783a53a903f2831691e171ab171497474cb7b6ef476da6c36a98f7038f78"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
