name = "Distant Horizons Benchmark"
author = "Steveplays28"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fa9b2969adf068988625841fd26df51190b252f3c44d01d2661520e35b73130"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
