name = "Distant Horizons Benchmark"
author = "Steveplays28"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f735413c0f6b894360f9b35cac2fd2479533998496bbc123a1bd803978430b52"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
