name = "Distant Horizons Benchmark"
author = "Steveplays28"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "237f7fd5e77a76f67ae50c505024c724c80749237fcc8b1d8743ae2bc3ec93fd"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
