name = "Distant Horizons Benchmark"
author = "Steveplays28"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "783e59f31fe8a25c341b168fc0cb1f1fd23afcde1f263d6c8fe2b211cde300ac"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
