name = "Distant Horizons Benchmark"
author = "Steveplays28"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df2f61f7d8594bf3c5e58c628c04eb2d519c360e19871c8efc65fcda22d9d13e"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
