name = "Distant Horizons Benchmark"
author = "Steveplays28"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daa4dd1ded02b88740cdf61eebd98da3a353b579f59da6967be62412f2b8b927"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
