name = "Distant Horizons Benchmark"
author = "Steveplays28"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "391968690b03aef996dc22960a0820bd072a5d4222a0be5a8669dba05957fe0c"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
